package appliedlife.pvtltd.SHEROES.enums;

/**
 * Created by Praveen_Singh on 28-03-2017.
 */

public enum  FeedParticipationEnum {
    LIKE_UNLIKE, COMMENT_REACTION,BOOKMARK_UNBOOKMARK,JOIN_INVITE,COMMUNITY_OWNER, ACTIVITY_FOR_REFRESH_FRAGMENT_LIST,
    ERROR_FEED_RESPONSE,ERROR_MY_COMMUNITIES,ERROR_TAG,ERROR_BOOK_MARK_LIST,
    ERROR_LIKE_UNLIKE,ERROR_COMMENT_REACTION,ERROR_BOOKMARK_UNBOOKMARK,ERROR_JOIN_INVITE,
    ERROR_AUTH_TOKEN,ERROR_COMMUNITY_OWNER,ERROR_SEARCH_DATA,ERROR_MEMBER,ERROR_REQUESTED,ERROR_MASTER_DATA,ERROR_CREATE_COMMUNITY,ERROR_SETTING,ERROR_ON_ONBOARDING;

}
